# Enable logging for MCUboot
CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=y

CONFIG_BOOT_MAX_IMG_SECTORS_AUTO=n
CONFIG_BOOT_MAX_IMG_SECTORS=512

CONFIG_MCUBOOT_SERIAL=n
CONFIG_BOOT_SERIAL_UART=n       
CONFIG_UART_CONSOLE=y
